// <auto-generated />
namespace EspapMiddleware.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RequestLog_Add_SupplierFiscalId_ReferenceNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequestLog_Add_SupplierFiscalId_ReferenceNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202309181538135_RequestLog_Add_SupplierFiscalId_ReferenceNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
